### ISSUE TITLE
FilePath Mapping issue 

### ISSUE THREAD

**Issue by cvdsouza** [Magicked/otx2crits#3]
Got the the following error when attempting to pull in new indicators : 

Traceback (most recent call last):
  File "otx2crits.py", line 389, in <module>
    main()
  File "otx2crits.py", line 385, in main
    otx2crits.execute()
  File "otx2crits.py", line 105, in execute
    _type = mapping[i['type']]
KeyError: u'FilePath'

**Comment by lolnate** [comment]
Thanks!
